name: tests
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  http: ^0.13.4


dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
  mocktail: ^0.2.0



